name: "04 - terraform apply to: staging"

on:
  pull_request:
    types: [closed]
    branches: [staging]

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"

permissions:
  contents: write
  id-token: write

jobs:
  check-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Check if merging from a release branch
      uses: actions/github-script@v7
      with:
        script: |
          const sourceBranch = context.payload.pull_request.head.ref;
          console.log(`Source branch: ${sourceBranch}`);
          if (!sourceBranch.startsWith('release-v')) {
            core.setFailed('This workflow can only be run when merging from a release branch (branch name starting with "release-v").');
          }

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    if: github.event.pull_request.merged == true
    needs: check-branch
    with:
      tf_cloud_organization: "deploymenttheory"
      tf_workspace: "terraform-jamfpro-staging"
      config_directory: "workload/terraform/jamfpro"
      debug: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  update-release:
    needs: [terraform-apply]
    uses: ./.github/workflows/update-release.yml
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}
      pull_request_number: ${{ github.event.pull_request.number }}
      merged_at: ${{ github.event.pull_request.merged_at }}
      merged_by: ${{ github.event.pull_request.merged_by.login }}
      target_environment: "staging"

  branch-cleanup:
    needs: [update-release]
    uses: ./.github/workflows/branch-cleanup.yml
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}

  send-notification:
    needs: [terraform-apply, update-release]
    if: ${{ always() && needs.terraform-apply.result != 'skipped' }}
    uses: ./.github/workflows/send-notification.yml
    with:
      environment: "Staging"
      result: ${{ needs.terraform-apply.result == 'success' && 'success' || 'failure' }}
      notification_channel: msteams
    secrets: inherit